// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package root.domain;

import org.springframework.beans.factory.annotation.Configurable;
import root.domain.PurchaseOrder;

privileged aspect PurchaseOrder_Roo_Configurable {
    
    declare @type: PurchaseOrder: @Configurable;
    
}
